repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/crate-ci/typos
    rev: v1.29.4
    hooks:
      - id: typos

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
        require_serial: true

  - repo: local
    hooks:
      - id: bandit
        name: bandit
        language: system
        entry: uv tool run bandit -v -c pyproject.toml -r src/* tests/*
        types: [python]
        
      - id: mypy
        name: mypy
        language: system
        entry: uv tool run hatch run mypy
        types: [python]
        pass_filenames: false

      - id: interrogate
        name: interrogate
        language: system
        entry: uv tool run interrogate --config pyproject.toml
        pass_filenames: false