from kedro.pipeline import Pipeline

from . import nodes


def create_pipeline(**kwargs) -> Pipeline:
    return Pipeline(
        nodes=[getattr(nodes, name) for name in nodes.__all__],
        namespace="silver",
        inputs={
            # landing
            "landing.reactome.reactome_pathways",
            "landing.onsides.vocab_meddra_adverse_effect",
            # Bronze
            "bronze.ontology.go_terms",
            "bronze.ontology.go_relations",
            "bronze.ontology.mondo_xrefs",
            "bronze.ontology.mondo_terms",
            "bronze.ontology.hp_terms",
            "bronze.ontology.hp_xrefs",
            "bronze.ontology.hp_relations",
            "bronze.ontology.uberon_terms",
            "bronze.ontology.uberon_relations",
            "bronze.bgee.gene_expressions_in_anatomy",
            "bronze.ctd.ctd_exposure_events",
            "bronze.reactome.reactome_relations",
            "bronze.drug_drug",
            "bronze.drug_gene",
            "bronze.drugbank.vocabulary",
            "bronze.disgenet.diseases",
            "bronze.disgenet.disgenet_phenotypes",
            "bronze.onsides.high_confidence",
            "bronze.opentargets.target_disease_associations",
            "bronze.opentargets.drug_indication",
            "bronze.opentargets.disease",
            "bronze.opentargets.target",
            "bronze.opentargets.disease_phenotype",
            "bronze.opentargets.drug_mechanism_of_action",
            "bronze.opentargets.drug_molecule",
            "bronze.opentargets.chembl_drugbank_mapping",
            "bronze.drugcentral.drug_disease",
            "bronze.drugcentral.drug",
            "bronze.drugcentral.drug_phenotype",
            "bronze.drugcentral.disease",
            "bronze.drugcentral.phenotype",
            "bronze.opentargets.ensembl_ncbi_mapping",
            "bronze.ppi.gene_gene",
            # silver
            "silver.edges.anatomy_gene",
            "silver.edges.anatomy_anatomy",
            "silver.edges.biological_process_gene",
            "silver.edges.exposure_biological_process",
            "silver.edges.biological_process_biological_process",
            "silver.edges.cellular_component_gene",
            "silver.edges.exposure_cellular_component",
            "silver.edges.cellular_component_cellular_component",
            "silver.edges.disease_disease",
            "silver.edges.exposure_disease",
            "silver.edges.drug_disease",
            "silver.edges.disease_gene",
            "silver.edges.disease_phenotype",
            "silver.edges.drug_drug",
            "silver.edges.drug_gene",
            "silver.edges.drug_phenotype",
            "silver.edges.exposure_gene",
            "silver.edges.exposure_exposure",
            "silver.edges.exposure_molecular_function",
            "silver.edges.molecular_function_gene",
            "silver.edges.pathway_gene",
            "silver.edges.phenotype_gene",
            "silver.edges.molecular_function_molecular_function",
            "silver.edges.pathway_pathway",
            "silver.edges.phenotype_phenotype",
            "silver.edges.gene_gene",
        },
    )
