from kedro.pipeline import pipeline

from . import nodes


def create_pipeline(**kwargs):
    return pipeline(
        [getattr(nodes, name) for name in nodes.__all__],
        namespace="gold",
        inputs={
            # Bronze
            "bronze.ontology.mondo_terms",
            "bronze.ontology.hp_terms",
            "bronze.ontology.uberon_terms",
            "bronze.ontology.go_terms",
            # Silver
            "silver.anatomy_protein",
            "silver.opentargets.opentargets_edges",
            "silver.exposure_protein",
            "silver.exposure_exposure",
            "silver.exposure_disease",
            "silver.exposure_biological_process",
            "silver.exposure_molecular_function",
            "silver.exposure_cellular_component",
            "silver.drug_drug",
            "silver.drug_protein",
            "silver.protein_biological_process",
            "silver.protein_cellular_component",
            "silver.protein_molecular_function",
            "silver.pathway_pathway",
            "silver.pathway_protein",
            "silver.disease_disease",
            "silver.cellular_component_cellular_component",
            "silver.biological_process_biological_process",
            "silver.molecular_function_molecular_function",
            "silver.disease_phenotype",
            "silver.anatomy_anatomy",
            "silver.drug_disease",
            "silver.disease_protein",
            "silver.effect_protein",
            "silver.phenotype_phenotype",
            "silver.drug_phenotype",
            # Nodes
            "gold.nodes.gene",
            "gold.nodes.anatomy",
            "gold.nodes.exposure",
            "gold.nodes.drug",
            "gold.nodes.disease",
            "gold.nodes.phenotype",
            "gold.nodes.biological_process",
            "gold.nodes.cellular_component",
            "gold.nodes.molecular_function",
            "gold.nodes.pathway",
            # Edges
            "gold.edges.anatomy_protein",
            "gold.edges.biological_process_protein",
            "gold.edges.cellular_component_protein",
            "gold.edges.disease_protein",
            "gold.edges.disease_disease",
            "gold.edges.drug_drug",
            "gold.edges.drug_protein",
            "gold.edges.drug_disease",
            "gold.edges.exposure_exposure",
            "gold.edges.exposure_protein",
            "gold.edges.exposure_disease",
            "gold.edges.molecular_function_protein",
            "gold.edges.pathway_pathway",
            "gold.edges.pathway_protein",
            "gold.edges.phenotype_protein",
            "gold.edges.exposure_biological_process",
            "gold.edges.exposure_molecular_function",
            "gold.edges.exposure_cellular_component",
            "gold.edges.cellular_component_cellular_component",
            "gold.edges.biological_process_biological_process",
            "gold.edges.molecular_function_molecular_function",
            "gold.edges.disease_phenotype",
            "gold.edges.phenotype_phenotype",
            "gold.edges.anatomy_anatomy",
            "gold.edges.drug_phenotype",
        },
    )
