export function Logo() {
  return (
    <span className="flex items-center gap-1">
      <svg
        aria-hidden="true"
        fill="none"
        height="22"
        viewBox="0 0 256 256"
        width="22"
        xmlns="http://www.w3.org/2000/svg"
      >
        <circle
          cx="128"
          cy="128"
          r="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="16"
        />
        <circle
          cx="96"
          cy="56"
          r="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="16"
        />
        <circle
          cx="200"
          cy="104"
          r="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="16"
        />
        <circle
          cx="200"
          cy="184"
          r="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="16"
        />
        <circle
          cx="56"
          cy="192"
          r="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="16"
        />
        <line
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="16"
          x1="118.25"
          x2="105.75"
          y1="106.07"
          y2="77.93"
        />
        <line
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="16"
          x1="177.23"
          x2="150.77"
          y1="111.59"
          y2="120.41"
        />
        <line
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="16"
          x1="181.06"
          x2="146.94"
          y1="169.27"
          y2="142.73"
        />
        <line
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="16"
          x1="110.06"
          x2="73.94"
          y1="143.94"
          y2="176.06"
        />
      </svg>
      <span
        className="whitespace-nowrap font-normal"
        style={{ fontSize: "1rem", lineHeight: "1", letterSpacing: "-0.015em" }}
      >
        OptimusKG
      </span>
    </span>
  );
}
