services:
   postgres:
        image: postgres:16.1
        container_name: drugcentral_postgres # TODO: Replace drugcentral to generic postgres dataset name
        ports:
            - 5432:5432
        restart: unless-stopped
        # NOTE: We don't need to persist the database because we only query it once.
        volumes:
            - .volumes/:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: optimuskg
            POSTGRES_PASSWORD: optimuskg
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: drugcentral
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "--username",
                    "optimuskg",
                    "--dbname",
                    "drugcentral",
                ]
            interval: 10s
            timeout: 5s
            retries: 5