biocypher:
  # Required
  dbms: neo4j
  schema_config_path: conf/base/biocypher/schema_config.yaml
  offline: true
  strict_mode: false
  # Optional
  debug: true
  log_to_disk: true
  log_directory: .biocypher/biocypher-log
  cache_directory: .biocypher/biocypher_cache
  output_directory: data/neo4j/import/
  
  tail_ontologies:
    go_biological_process:
      url: "http://purl.obolibrary.org/obo/go/extensions/go-plus.owl"
      head_join_node: biological process # Biolink’s BiologicalProcess class is the umbrella for any process-oriented concept (e.g. signaling, metabolism, gene expression) 
      tail_join_node: biological_process # GO’s biological_process node (GO:0008150) is the single root of all process terms in GO
      merge_nodes: false

    go_cellular_component:
      url: "http://purl.obolibrary.org/obo/go/extensions/go-plus.owl"
      head_join_node: cellular component # Biolink’s CellularComponent class is the umbrella for any component-oriented concept (e.g. organelle, membrane, cytoskeleton)
      tail_join_node: cellular_component # GO’s cellular_component node (GO:0005575) is the single root of all component terms in GO
      merge_nodes: false

    go_molecular_function:
      url: "http://purl.obolibrary.org/obo/go/extensions/go-plus.owl"
      head_join_node: molecular activity # Biolink’s MolecularActivity class (https://w3id.org/biolink/vocab/MolecularActivity)
      tail_join_node: molecular_function # GO’s molecular functions represent molecular-level activities performed by gene products, such as “catalysis” or “transcription regulator activity”. (https://geneontology.org/docs/ontology-documentation/)
      merge_nodes: false

    uberon:
      url: "http://purl.obolibrary.org/obo/uberon.owl"
      head_join_node: anatomical entity # Biolink’s AnatomicalEntity class is the umbrella for any anatomical concept (e.g. organ, tissue, cell)
      tail_join_node: anatomical entity # UBERON’s anatomical entity node (UBERON:0001062) is the single root of all anatomical terms in UBERON
      merge_nodes: false
      
neo4j:
  database_name: neo4j
  wipe: true

  uri: bolt://localhost:7687
  user: ""
  password: ""

  delimiter: ";"
  array_delimiter: "|"
  quote_character: '"'

  skip_duplicate_nodes: false
  skip_bad_relationships: false

  labels_order: "Ascending" # Note: This is not being used by biocypher. Possible options: "Alphabetcal", "Ascending", "Descending", "Leaves". See https://github.com/biocypher/biocypher/blob/main/biocypher/output/write/_batch_writer.py#L289