# ---
# Nodes
# ---

gene: # A region (or regions) that includes all of the sequence elements necessary to encode a functional transcript. (https://biolink.github.io/biolink-model/Gene/)                   
  represented_as: node
  input_label: gene
  properties:
    name: str
    source: str

anatomy: # Biological entity that is either an individual member of a biological species or constitutes the structural organization of an individual member of a biological species. (http://purl.obolibrary.org/obo/UBERON_0001062)
  is_a: anatomical entity
  represented_as: node
  input_label: anatomy
  properties:
    name: str
    source: str
    definition: str
    xrefs: str[]
    synonyms: str[]
    ontology_description: str
    ontology_title: str
    ontology_license: str
    ontology_version: str

exposure: # A environmental exposure is a factor relating to abiotic processes in the environment including sunlight (UV-B), atmospheric (heat, cold, general pollution) and water-born contaminants. (https://biolink.github.io/biolink-model/EnvironmentalExposure/)
  is_a: environmental exposure
  represented_as: node
  input_label: exposure
  properties:
    name: str
    source: str

drug: # A substance that is used to treat, prevent, or diagnose a disease or condition (https://biolink.github.io/biolink-model/Drug/)
  represented_as: node
  input_label: drug
  properties:
    name: str
    source: str

disease: # A disease or phenotypic feature (https://biolink.github.io/biolink-model/Disease/)
  represented_as: node
  input_label: disease
  properties:
    name: str
    source: str
    definition: str
    xrefs: str[]
    synonyms: str[]
    ontology_description: str
    ontology_title: str
    ontology_license: str
    ontology_version: str

phenotype: # A phenotypic feature (https://biolink.github.io/biolink-model/PhenotypicFeature/)
  is_a: phenotypic feature
  represented_as: node
  input_label: phenotype
  properties:
    name: str
    source: str
    definition: str
    xrefs: str[]
    synonyms: str[]
    ontology_description: str
    ontology_title: str
    ontology_license: str
    ontology_version: str

biological process:
  represented_as: node
  input_label: biological_process
  properties:
    name: str
    source: str
    definition: str
    xrefs: str[]
    synonyms: str[]
    ontology_description: str
    ontology_title: str
    ontology_license: str
    ontology_version: str

cellular component:
  represented_as: node
  input_label: cellular_component
  properties:
    name: str
    source: str
    definition: str
    xrefs: str[]
    synonyms: str[]
    ontology_description: str
    ontology_title: str
    ontology_license: str
    ontology_version: str

molecular function:
  represented_as: node
  input_label: molecular_function
  properties:
    name: str
    source: str
    definition: str
    xrefs: str[]
    synonyms: str[]
    ontology_description: str
    ontology_title: str
    ontology_license: str
    ontology_version: str

pathway:
  represented_as: node
  input_label: pathway # Biolink’s Pathway class (https://biolink.github.io/biolink-model/Pathway/)
  properties:
    name: str
    source: str

# ---
# Edges
# ---

anatomy protein:
  is_a: linked to
  represented_as: edge
  input_label: anatomy_protein
  properties:
    relation_type: str
    undirected: str

anatomy anatomy:
  is_a: related to # A relationship that is asserted between two named things (https://biolink.github.io/biolink-model/related_to/)
  represented_as: edge
  input_label: anatomy_anatomy
  properties:
    relation_type: str
    undirected: str

exposure disease:
  is_a: linked to # holds between a disease and an environmental exposure (https://biolink.github.io/biolink-model/linked_to/)
  represented_as: edge
  input_label: exposure_disease
  properties:
    relation_type: str
    undirected: str

exposure exposure:
  is_a: has_part # holds between a part and its whole (https://biolink.github.io/biolink-model/has_part/)
  represented_as: edge
  input_label: exposure_exposure
  properties:
    relation_type: str
    undirected: str

exposure protein:
  is_a: interacts_with # holds between a gene or gene product and an environmental exposure (https://biolink.github.io/biolink-model/interacts_with/)
  represented_as: edge
  input_label: exposure_protein
  properties:
    relation_type: str
    undirected: str

disease protein:
  is_a: related to # A relationship that is asserted between two named things (https://biolink.github.io/biolink-model/related_to/)
  represented_as: edge
  input_label: disease_protein
  properties:
    relation_type: str
    undirected: str

disease disease:
  is_a: related to # A relationship that is asserted between two named things (https://biolink.github.io/biolink-model/related_to/)
  represented_as: edge
  input_label: disease_disease
  properties:
    relation_type: str
    undirected: str

phenotype protein:
  is_a: related to # A relationship that is asserted between two named things (https://biolink.github.io/biolink-model/related_to/)
  represented_as: edge
  input_label: phenotype_protein
  properties:
    relation_type: str
    undirected: str

drug protein:
  is_a: physically interacts with # holds between two entities that make physical contact as part of some interaction (https://biolink.github.io/biolink-model/physically_interacts_with/)
  represented_as: edge
  input_label: drug_protein
  properties:
    relation_type: str
    undirected: str

drug drug:
  is_a: physically interacts with # holds between two entities that make physical contact as part of some interaction (https://biolink.github.io/biolink-model/physically_interacts_with/)
  represented_as: edge
  input_label: drug_drug
  properties:
    relation_type: str
    undirected: str

drug disease:
  is_a: related to # A relationship that is asserted between two named things (https://biolink.github.io/biolink-model/related_to/)
  represented_as: edge
  input_label: drug_disease
  properties:
    relation_type: str
    undirected: str

drug phenotype:
  is_a: related to
  represented_as: edge
  input_label: drug_phenotype
  properties:
    relation_type: str
    undirected: str

biological process protein:
  is_a: regulates # holds between a gene or gene product and a biological process (https://biolink.github.io/biolink-model/regulates/)
  represented_as: edge
  input_label: biological_process_protein
  properties:
    relation_type: str
    undirected: str

cellular component protein:
  is_a: regulates # holds between a gene or gene product and a cellular component (https://biolink.github.io/biolink-model/regulates/)
  represented_as: edge
  input_label: cellular_component_protein
  properties:
    relation_type: str
    undirected: str

molecular function protein:
  is_a: regulates # holds between a gene or gene product and a molecular function (https://biolink.github.io/biolink-model/regulates/)
  represented_as: edge
  input_label: molecular_function_protein
  properties:
    relation_type: str
    undirected: str

pathway pathway:
  is_a: has_part # holds between a part and its whole (https://biolink.github.io/biolink-model/has_part/)
  represented_as: edge
  input_label: pathway_pathway
  properties:
    relation_type: str
    undirected: str

pathway protein:
  is_a: has_part # holds between a part and its whole (https://biolink.github.io/biolink-model/has_part/)
  represented_as: edge
  input_label: pathway_protein
  properties:
    relation_type: str
    undirected: str

exposure biological process:
  is_a: related to
  represented_as: edge
  input_label: exposure_biological_process
  properties:
    relation_type: str
    undirected: str

exposure molecular function:
  is_a: related to
  represented_as: edge
  input_label: exposure_molecular_function
  properties:
    relation_type: str
    undirected: str
    
exposure cellular component:
  is_a: related to
  represented_as: edge
  input_label: exposure_cellular_component
  properties:
    relation_type: str
    undirected: str

cellular component cellular component:
  is_a: has_part
  represented_as: edge
  input_label: cellular_component_cellular_component
  properties:
    relation_type: str
    undirected: str

biological process biological process:
  is_a: has_part
  represented_as: edge
  input_label: biological_process_biological_process
  properties:
    relation_type: str
    undirected: str

molecular function molecular function:
  is_a: has_part
  represented_as: edge
  input_label: molecular_function_molecular_function
  properties:
    relation_type: str
    undirected: str

disease phenotype:
  is_a: related to
  represented_as: edge
  input_label: disease_phenotype
  properties:
    relation_type: str
    undirected: str

phenotype phenotype:
  is_a: has_part
  represented_as: edge
  input_label: phenotype_phenotype
  properties:
    relation_type: str
    undirected: str