name: Release

on:
  push:
    branches: main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get package version
        id: package_version
        run: |
          echo "version=$(cat pyproject.toml | grep '^version = ' | head -1 | sed 's/version = \"\([^\"]*\)\"/\1/')" >>$GITHUB_OUTPUT

      - name: Create Release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package_version.outputs.version }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false