name: integration

on:
  pull_request:

env:
  CLICOLOR: 1
  PYTHON_VERSION: 3.12

jobs:
  install-uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        id: setup-uv
        with:
          enable-cache: true
          ignore-nothing-to-cache: true
          pyproject-file: "pyproject.toml"
          python-version: ${{ env.PYTHON_VERSION }}
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Log if uv cache was restored
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"

      - name: Print the installed uv version
        run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"

  quality-check:
    runs-on: ubuntu-latest
    needs: install-uv
    steps:
      - name: Spell Check
        uses: crate-ci/typos@v1.29.4

      - name: Run MyPy type checker
        run: uv tool run hatch run mypy
