name: Deploy Kedro Viz

on:
  push:
    branches: main

env:
  PYTHON_VERSION: 3.12

jobs:
  uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        id: setup-uv
        with:
          enable-cache: true
          ignore-nothing-to-cache: true
          pyproject-file: "pyproject.toml"
          python-version: ${{ env.PYTHON_VERSION }}
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install the project dependencies
        run: uv run kedro viz build

  upload-build-folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload file to Vercel Blob
        uses: dartilesm/vercel-blob-action@v2
        with:
          source: "build/"
          destination: "build/" # NOTE: we could use something like "${{ github.sha }}/build/" but we want to re-write the folder in the blob storage.
          read-write-token: ${{ secrets.BLOB_READ_WRITE_TOKEN }}

