name: Release

on:
  push:
    branches: main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Read project version
        id: project_version
        uses: maybe-hello-world/pyproject-check-version@v4
        with:
          pyproject-path: pyproject.toml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.project_version.outputs.local_version }}
          name: Release ${{ steps.project_version.outputs.local_version }}
          draft: false
          prerelease: false

  publish:
    name: Publish client
    needs: release
    uses: ./.github/workflows/publish-pypi.yml
    with:
      package-dir: packages/optimuskg
